name: Build and deploy notebook2rest to AWS
description: 'Converts Jupyter Notebooks to a REST API, containerizes it, and deploys to AWS.'
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
  aws_region:
    description: 'AWS Region'
    required: true
  eks_cluster_name:
    description: 'The name of your AWS EKS Cluster'
    required: true
    default: 'notebook2rest_cluster'
  ecr_repository:
    description: 'The ECR repository name'
    required: true
    default: 'notebook2rest/api'
  notebook_repository_name:
    description: 'The name of the notebook repository'
    required: true
  notebook_repository_url:
    description: 'The URL of the notebook repository'
    required: true

runs:
  using: "composite"

  steps:
    - name: Checkout notebook repository
      uses: actions/checkout@v4
      
    - name: Retrieve the notebook repository
      run: |
        git clone ${{ inputs.notebook_repository_url }}
      shell: bash
  
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # Run Notebook2REST
    - name: Install notebook2rest
      shell: bash
      run: |
        git clone https://github.com/devops-notebook2rest/notebook2rest.git

    - name: Run notebook2rest
      shell: bash
      run: |
        cd notebook2rest
        python3 src/main.py ../${{ inputs.notebook_repository_name }}

    - name: Inject custom requirements
      shell: bash
      run: |
        if [ -f "n2r_requirements.txt" ]; then
          echo "Injecting custom dependencies..."
          echo "" >> notebook2rest/build/requirements.txt
          cat n2r_requirements.txt >> notebook2rest/build/requirements.txt
        else
          echo "Proceeding with templated dependencies."
        fi

    # AWS setup
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}

    # ECR login
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Build & push the image
    - name: Build, tag, and push docker image
      shell: bash
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        EKS_CLUSTER_NAME: ${{inputs.eks_cluster_name}}
        REPOSITORY: ${{inputs.ecr_repository}}
        IMAGE_TAG: ${{ github.sha }}-${{ github.run_number }}
      run: |
        docker build \
          --build-arg GIT_SHA=${{ github.sha }} \
          --build-arg BUILD_NUMBER=${{ github.run_number }} \
          --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG notebook2rest/build
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    # Points it to the AWS cluster
    - name: Configure kubeconfig
      shell: bash
      run: aws eks update-kubeconfig --region ${{inputs.aws_region}} --name ${{inputs.eks_cluster_name}}

    # Redeploys helm chart
    - name: Deploy Helm chart
      shell: bash
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{inputs.ecr_repository}}
        IMAGE_TAG: ${{ github.sha }}-${{ github.run_number }}
      run: |
        cd notebook2rest
        helm upgrade --install my-api templates/helm --namespace default --set image.repository=$REGISTRY/$REPOSITORY --set image.tag=$IMAGE_TAG
